# 使用するコンテナを列挙する
resources:
  containers:
    - container: rust
      image: rust:latest

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        stable:
          rust_toolchain: stable
        beta:
          rust_toolchain: beta

    steps:
      - bash: |
          set -e
          if command -v rustup; then
            rustup update $TOOLCHAIN
            rustup default $TOOLCHAIN
          else
            curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain $RUST_TOOLCHAIN -y
            echo "##vso[task.prependpath]$HOME/.cargo/bin"
          fi
          rustup toolchain remove $RUST_TOOLCHAIN && $HOME/.cargo/bin/rustup toolchain add $RUST_TOOLCHAIN
          rustup component add rustfmt
          rustup component add clippy
        displayName: Install Rust

      - script: cargo fmt --all -- --check
        displayName: Run formatter

      - script: cargo clippy -- -D warnings
        displayName: Run linter

      - script: cargo build
        displayName: Build